local canalave_0 = DoorSlot("canalave","0")
local canalave_0_hub = DoorSlotHub("canalave","0",canalave_0)
canalave_0:setHubIcon(canalave_0_hub)
local canalave_1 = DoorSlot("canalave","1")
local canalave_1_hub = DoorSlotHub("canalave","1",canalave_1)
canalave_1:setHubIcon(canalave_1_hub)
local canalave_2 = DoorSlot("canalave","2")
local canalave_2_hub = DoorSlotHub("canalave","2",canalave_2)
canalave_2:setHubIcon(canalave_2_hub)
local canalave_3 = DoorSlot("canalave","3")
local canalave_3_hub = DoorSlotHub("canalave","3",canalave_3)
canalave_3:setHubIcon(canalave_3_hub)
local canalave_4 = DoorSlot("canalave","4")
local canalave_4_hub = DoorSlotHub("canalave","4",canalave_4)
canalave_4:setHubIcon(canalave_4_hub)
local canalave_5 = DoorSlot("canalave","5")
local canalave_5_hub = DoorSlotHub("canalave","5",canalave_5)
canalave_5:setHubIcon(canalave_5_hub)
local canalave_6 = DoorSlot("canalave","6")
local canalave_6_hub = DoorSlotHub("canalave","6",canalave_6)
canalave_6:setHubIcon(canalave_6_hub)
local canalave_7 = DoorSlot("canalave","7")
local canalave_7_hub = DoorSlotHub("canalave","7",canalave_7)
canalave_7:setHubIcon(canalave_7_hub)
local canalave_8 = DoorSlot("canalave","8")
local canalave_8_hub = DoorSlotHub("canalave","8",canalave_8)
canalave_8:setHubIcon(canalave_8_hub)
local canalave_9 = DoorSlot("canalave","9")
local canalave_9_hub = DoorSlotHub("canalave","9",canalave_9)
canalave_9:setHubIcon(canalave_9_hub)
local canalave_10 = DoorSlot("canalave","10")
local canalave_10_hub = DoorSlotHub("canalave","10",canalave_10)
canalave_10:setHubIcon(canalave_10_hub)
local canalave_11 = DoorSlot("canalave","11")
local canalave_11_hub = DoorSlotHub("canalave","11",canalave_11)
canalave_11:setHubIcon(canalave_11_hub)
local canalave_12 = DoorSlot("canalave","12")
local canalave_12_hub = DoorSlotHub("canalave","12",canalave_12)
canalave_12:setHubIcon(canalave_12_hub)
