local celestic_0 = DoorSlot("celestic","0")
local celestic_0_hub = DoorSlotHub("celestic","0",celestic_0)
celestic_0:setHubIcon(celestic_0_hub)
local celestic_1 = DoorSlot("celestic","1")
local celestic_1_hub = DoorSlotHub("celestic","1",celestic_1)
celestic_1:setHubIcon(celestic_1_hub)
local celestic_2 = DoorSlot("celestic","2")
local celestic_2_hub = DoorSlotHub("celestic","2",celestic_2)
celestic_2:setHubIcon(celestic_2_hub)
local celestic_3 = DoorSlot("celestic","3")
local celestic_3_hub = DoorSlotHub("celestic","3",celestic_3)
celestic_3:setHubIcon(celestic_3_hub)
local celestic_4 = DoorSlot("celestic","4")
local celestic_4_hub = DoorSlotHub("celestic","4",celestic_4)
celestic_4:setHubIcon(celestic_4_hub)
local celestic_5 = DoorSlot("celestic","5")
local celestic_5_hub = DoorSlotHub("celestic","5",celestic_5)
celestic_5:setHubIcon(celestic_5_hub)
local celestic_6 = DoorSlot("celestic","6")
local celestic_6_hub = DoorSlotHub("celestic","6",celestic_6)
celestic_6:setHubIcon(celestic_6_hub)
local celestic_7 = DoorSlot("celestic","7")
local celestic_7_hub = DoorSlotHub("celestic","7",celestic_7)
celestic_7:setHubIcon(celestic_7_hub)
local celestic_8 = DoorSlot("celestic","8")
local celestic_8_hub = DoorSlotHub("celestic","8",celestic_8)
celestic_8:setHubIcon(celestic_8_hub)
