local coronet_peak_0 = DoorSlot("coronet_peak","0")
local coronet_peak_0_hub = DoorSlotHub("coronet_peak","0",coronet_peak_0)
coronet_peak_0:setHubIcon(coronet_peak_0_hub)
local coronet_peak_1 = DoorSlot("coronet_peak","1")
local coronet_peak_1_hub = DoorSlotHub("coronet_peak","1",coronet_peak_1)
coronet_peak_1:setHubIcon(coronet_peak_1_hub)
local coronet_peak_2 = DoorSlot("coronet_peak","2")
local coronet_peak_2_hub = DoorSlotHub("coronet_peak","2",coronet_peak_2)
coronet_peak_2:setHubIcon(coronet_peak_2_hub)
local coronet_peak_3 = DoorSlot("coronet_peak","3")
local coronet_peak_3_hub = DoorSlotHub("coronet_peak","3",coronet_peak_3)
coronet_peak_3:setHubIcon(coronet_peak_3_hub)
local coronet_peak_4 = DoorSlot("coronet_peak","4")
local coronet_peak_4_hub = DoorSlotHub("coronet_peak","4",coronet_peak_4)
coronet_peak_4:setHubIcon(coronet_peak_4_hub)
local coronet_peak_5 = DoorSlot("coronet_peak","5")
local coronet_peak_5_hub = DoorSlotHub("coronet_peak","5",coronet_peak_5)
coronet_peak_5:setHubIcon(coronet_peak_5_hub)
