local coronet_0 = DoorSlot("coronet","0")
local coronet_0_hub = DoorSlotHub("coronet","0",coronet_0)
coronet_0:setHubIcon(coronet_0_hub)
local coronet_1 = DoorSlot("coronet","1")
local coronet_1_hub = DoorSlotHub("coronet","1",coronet_1)
coronet_1:setHubIcon(coronet_1_hub)
local coronet_2 = DoorSlot("coronet","2")
local coronet_2_hub = DoorSlotHub("coronet","2",coronet_2)
coronet_2:setHubIcon(coronet_2_hub)
local coronet_3 = DoorSlot("coronet","3")
local coronet_3_hub = DoorSlotHub("coronet","3",coronet_3)
coronet_3:setHubIcon(coronet_3_hub)
local coronet_4 = DoorSlot("coronet","4")
local coronet_4_hub = DoorSlotHub("coronet","4",coronet_4)
coronet_4:setHubIcon(coronet_4_hub)
local coronet_5 = DoorSlot("coronet","5")
local coronet_5_hub = DoorSlotHub("coronet","5",coronet_5)
coronet_5:setHubIcon(coronet_5_hub)
local coronet_6 = DoorSlot("coronet","6")
local coronet_6_hub = DoorSlotHub("coronet","6",coronet_6)
coronet_6:setHubIcon(coronet_6_hub)
local coronet_7 = DoorSlot("coronet","7")
local coronet_7_hub = DoorSlotHub("coronet","7",coronet_7)
coronet_7:setHubIcon(coronet_7_hub)
local coronet_8 = DoorSlot("coronet","8")
local coronet_8_hub = DoorSlotHub("coronet","8",coronet_8)
coronet_8:setHubIcon(coronet_8_hub)
local coronet_9 = DoorSlot("coronet","9")
local coronet_9_hub = DoorSlotHub("coronet","9",coronet_9)
coronet_9:setHubIcon(coronet_9_hub)
local coronet_10 = DoorSlot("coronet","10")
local coronet_10_hub = DoorSlotHub("coronet","10",coronet_10)
coronet_10:setHubIcon(coronet_10_hub)
local coronet_11 = DoorSlot("coronet","11")
local coronet_11_hub = DoorSlotHub("coronet","11",coronet_11)
coronet_11:setHubIcon(coronet_11_hub)
local coronet_12 = DoorSlot("coronet","12")
local coronet_12_hub = DoorSlotHub("coronet","12",coronet_12)
coronet_12:setHubIcon(coronet_12_hub)
local coronet_13 = DoorSlot("coronet","13")
local coronet_13_hub = DoorSlotHub("coronet","13",coronet_13)
coronet_13:setHubIcon(coronet_13_hub)
local coronet_14 = DoorSlot("coronet","14")
local coronet_14_hub = DoorSlotHub("coronet","14",coronet_14)
coronet_14:setHubIcon(coronet_14_hub)
local coronet_15 = DoorSlot("coronet","15")
local coronet_15_hub = DoorSlotHub("coronet","15",coronet_15)
coronet_15:setHubIcon(coronet_15_hub)
local coronet_16 = DoorSlot("coronet","16")
local coronet_16_hub = DoorSlotHub("coronet","16",coronet_16)
coronet_16:setHubIcon(coronet_16_hub)
local coronet_17 = DoorSlot("coronet","17")
local coronet_17_hub = DoorSlotHub("coronet","17",coronet_17)
coronet_17:setHubIcon(coronet_17_hub)
local coronet_18 = DoorSlot("coronet","18")
local coronet_18_hub = DoorSlotHub("coronet","18",coronet_18)
coronet_18:setHubIcon(coronet_18_hub)
local coronet_19 = DoorSlot("coronet","19")
local coronet_19_hub = DoorSlotHub("coronet","19",coronet_19)
coronet_19:setHubIcon(coronet_19_hub)
