local eterna_forest_0 = DoorSlot("eterna_forest","0")
local eterna_forest_0_hub = DoorSlotHub("eterna_forest","0",eterna_forest_0)
eterna_forest_0:setHubIcon(eterna_forest_0_hub)
local eterna_forest_1 = DoorSlot("eterna_forest","1")
local eterna_forest_1_hub = DoorSlotHub("eterna_forest","1",eterna_forest_1)
eterna_forest_1:setHubIcon(eterna_forest_1_hub)
local eterna_forest_2 = DoorSlot("eterna_forest","2")
local eterna_forest_2_hub = DoorSlotHub("eterna_forest","2",eterna_forest_2)
eterna_forest_2:setHubIcon(eterna_forest_2_hub)
