local eterna_0 = DoorSlot("eterna","0")
local eterna_0_hub = DoorSlotHub("eterna","0",eterna_0)
eterna_0:setHubIcon(eterna_0_hub)
local eterna_1 = DoorSlot("eterna","1")
local eterna_1_hub = DoorSlotHub("eterna","1",eterna_1)
eterna_1:setHubIcon(eterna_1_hub)
local eterna_2 = DoorSlot("eterna","2")
local eterna_2_hub = DoorSlotHub("eterna","2",eterna_2)
eterna_2:setHubIcon(eterna_2_hub)
local eterna_3 = DoorSlot("eterna","3")
local eterna_3_hub = DoorSlotHub("eterna","3",eterna_3)
eterna_3:setHubIcon(eterna_3_hub)
local eterna_4 = DoorSlot("eterna","4")
local eterna_4_hub = DoorSlotHub("eterna","4",eterna_4)
eterna_4:setHubIcon(eterna_4_hub)
local eterna_5 = DoorSlot("eterna","5")
local eterna_5_hub = DoorSlotHub("eterna","5",eterna_5)
eterna_5:setHubIcon(eterna_5_hub)
local eterna_6 = DoorSlot("eterna","6")
local eterna_6_hub = DoorSlotHub("eterna","6",eterna_6)
eterna_6:setHubIcon(eterna_6_hub)
local eterna_7 = DoorSlot("eterna","7")
local eterna_7_hub = DoorSlotHub("eterna","7",eterna_7)
eterna_7:setHubIcon(eterna_7_hub)
local eterna_8 = DoorSlot("eterna","8")
local eterna_8_hub = DoorSlotHub("eterna","8",eterna_8)
eterna_8:setHubIcon(eterna_8_hub)
local eterna_9 = DoorSlot("eterna","9")
local eterna_9_hub = DoorSlotHub("eterna","9",eterna_9)
eterna_9:setHubIcon(eterna_9_hub)
local eterna_10 = DoorSlot("eterna","10")
local eterna_10_hub = DoorSlotHub("eterna","10",eterna_10)
eterna_10:setHubIcon(eterna_10_hub)
local eterna_11 = DoorSlot("eterna","11")
local eterna_11_hub = DoorSlotHub("eterna","11",eterna_11)
eterna_11:setHubIcon(eterna_11_hub)
local eterna_12 = DoorSlot("eterna","12")
local eterna_12_hub = DoorSlotHub("eterna","12",eterna_12)
eterna_12:setHubIcon(eterna_12_hub)
local eterna_13 = DoorSlot("eterna","13")
local eterna_13_hub = DoorSlotHub("eterna","13",eterna_13)
eterna_13:setHubIcon(eterna_13_hub)
