local eterna_galactic_0 = DoorSlot("eterna_galactic","0")
local eterna_galactic_0_hub = DoorSlotHub("eterna_galactic","0",eterna_galactic_0)
eterna_galactic_0:setHubIcon(eterna_galactic_0_hub)
local eterna_galactic_1 = DoorSlot("eterna_galactic","1")
local eterna_galactic_1_hub = DoorSlotHub("eterna_galactic","1",eterna_galactic_1)
eterna_galactic_1:setHubIcon(eterna_galactic_1_hub)
local eterna_galactic_2 = DoorSlot("eterna_galactic","2")
local eterna_galactic_2_hub = DoorSlotHub("eterna_galactic","2",eterna_galactic_2)
eterna_galactic_2:setHubIcon(eterna_galactic_2_hub)
local eterna_galactic_3 = DoorSlot("eterna_galactic","3")
local eterna_galactic_3_hub = DoorSlotHub("eterna_galactic","3",eterna_galactic_3)
eterna_galactic_3:setHubIcon(eterna_galactic_3_hub)
local eterna_galactic_4 = DoorSlot("eterna_galactic","4")
local eterna_galactic_4_hub = DoorSlotHub("eterna_galactic","4",eterna_galactic_4)
eterna_galactic_4:setHubIcon(eterna_galactic_4_hub)
local eterna_galactic_5 = DoorSlot("eterna_galactic","5")
local eterna_galactic_5_hub = DoorSlotHub("eterna_galactic","5",eterna_galactic_5)
eterna_galactic_5:setHubIcon(eterna_galactic_5_hub)
local eterna_galactic_6 = DoorSlot("eterna_galactic","6")
local eterna_galactic_6_hub = DoorSlotHub("eterna_galactic","6",eterna_galactic_6)
eterna_galactic_6:setHubIcon(eterna_galactic_6_hub)
local eterna_galactic_7 = DoorSlot("eterna_galactic","7")
local eterna_galactic_7_hub = DoorSlotHub("eterna_galactic","7",eterna_galactic_7)
eterna_galactic_7:setHubIcon(eterna_galactic_7_hub)
local eterna_galactic_8 = DoorSlot("eterna_galactic","8")
local eterna_galactic_8_hub = DoorSlotHub("eterna_galactic","8",eterna_galactic_8)
eterna_galactic_8:setHubIcon(eterna_galactic_8_hub)
local eterna_galactic_9 = DoorSlot("eterna_galactic","9")
local eterna_galactic_9_hub = DoorSlotHub("eterna_galactic","9",eterna_galactic_9)
eterna_galactic_9:setHubIcon(eterna_galactic_9_hub)
