local fight_area_0 = DoorSlot("fight_area","0")
local fight_area_0_hub = DoorSlotHub("fight_area","0",fight_area_0)
fight_area_0:setHubIcon(fight_area_0_hub)
local fight_area_1 = DoorSlot("fight_area","1")
local fight_area_1_hub = DoorSlotHub("fight_area","1",fight_area_1)
fight_area_1:setHubIcon(fight_area_1_hub)
local fight_area_2 = DoorSlot("fight_area","2")
local fight_area_2_hub = DoorSlotHub("fight_area","2",fight_area_2)
fight_area_2:setHubIcon(fight_area_2_hub)
local fight_area_3 = DoorSlot("fight_area","3")
local fight_area_3_hub = DoorSlotHub("fight_area","3",fight_area_3)
fight_area_3:setHubIcon(fight_area_3_hub)
local fight_area_4 = DoorSlot("fight_area","4")
local fight_area_4_hub = DoorSlotHub("fight_area","4",fight_area_4)
fight_area_4:setHubIcon(fight_area_4_hub)
local fight_area_5 = DoorSlot("fight_area","5")
local fight_area_5_hub = DoorSlotHub("fight_area","5",fight_area_5)
fight_area_5:setHubIcon(fight_area_5_hub)
local fight_area_6 = DoorSlot("fight_area","6")
local fight_area_6_hub = DoorSlotHub("fight_area","6",fight_area_6)
fight_area_6:setHubIcon(fight_area_6_hub)
local fight_area_7 = DoorSlot("fight_area","7")
local fight_area_7_hub = DoorSlotHub("fight_area","7",fight_area_7)
fight_area_7:setHubIcon(fight_area_7_hub)
