local floaroma_0 = DoorSlot("floaroma","0")
local floaroma_0_hub = DoorSlotHub("floaroma","0",floaroma_0)
floaroma_0:setHubIcon(floaroma_0_hub)
local floaroma_1 = DoorSlot("floaroma","1")
local floaroma_1_hub = DoorSlotHub("floaroma","1",floaroma_1)
floaroma_1:setHubIcon(floaroma_1_hub)
local floaroma_2 = DoorSlot("floaroma","2")
local floaroma_2_hub = DoorSlotHub("floaroma","2",floaroma_2)
floaroma_2:setHubIcon(floaroma_2_hub)
local floaroma_3 = DoorSlot("floaroma","3")
local floaroma_3_hub = DoorSlotHub("floaroma","3",floaroma_3)
floaroma_3:setHubIcon(floaroma_3_hub)
local floaroma_4 = DoorSlot("floaroma","4")
local floaroma_4_hub = DoorSlotHub("floaroma","4",floaroma_4)
floaroma_4:setHubIcon(floaroma_4_hub)
local floaroma_5 = DoorSlot("floaroma","5")
local floaroma_5_hub = DoorSlotHub("floaroma","5",floaroma_5)
floaroma_5:setHubIcon(floaroma_5_hub)
local floaroma_6 = DoorSlot("floaroma","6")
local floaroma_6_hub = DoorSlotHub("floaroma","6",floaroma_6)
floaroma_6:setHubIcon(floaroma_6_hub)
local floaroma_7 = DoorSlot("floaroma","7")
local floaroma_7_hub = DoorSlotHub("floaroma","7",floaroma_7)
floaroma_7:setHubIcon(floaroma_7_hub)
local floaroma_8 = DoorSlot("floaroma","8")
local floaroma_8_hub = DoorSlotHub("floaroma","8",floaroma_8)
floaroma_8:setHubIcon(floaroma_8_hub)
