local floaroma_meadow_0 = DoorSlot("floaroma_meadow","0")
local floaroma_meadow_0_hub = DoorSlotHub("floaroma_meadow","0",floaroma_meadow_0)
floaroma_meadow_0:setHubIcon(floaroma_meadow_0_hub)
local floaroma_meadow_1 = DoorSlot("floaroma_meadow","1")
local floaroma_meadow_1_hub = DoorSlotHub("floaroma_meadow","1",floaroma_meadow_1)
floaroma_meadow_1:setHubIcon(floaroma_meadow_1_hub)
local floaroma_meadow_2 = DoorSlot("floaroma_meadow","2")
local floaroma_meadow_2_hub = DoorSlotHub("floaroma_meadow","2",floaroma_meadow_2)
floaroma_meadow_2:setHubIcon(floaroma_meadow_2_hub)
