local fuego_ironworks_0 = DoorSlot("fuego_ironworks","0")
local fuego_ironworks_0_hub = DoorSlotHub("fuego_ironworks","0",fuego_ironworks_0)
fuego_ironworks_0:setHubIcon(fuego_ironworks_0_hub)
local fuego_ironworks_1 = DoorSlot("fuego_ironworks","1")
local fuego_ironworks_1_hub = DoorSlotHub("fuego_ironworks","1",fuego_ironworks_1)
fuego_ironworks_1:setHubIcon(fuego_ironworks_1_hub)
