local galactic_hq_0 = DoorSlot("galactic_hq","0")
local galactic_hq_0_hub = DoorSlotHub("galactic_hq","0",galactic_hq_0)
galactic_hq_0:setHubIcon(galactic_hq_0_hub)
local galactic_hq_1 = DoorSlot("galactic_hq","1")
local galactic_hq_1_hub = DoorSlotHub("galactic_hq","1",galactic_hq_1)
galactic_hq_1:setHubIcon(galactic_hq_1_hub)
local galactic_hq_2 = DoorSlot("galactic_hq","2")
local galactic_hq_2_hub = DoorSlotHub("galactic_hq","2",galactic_hq_2)
galactic_hq_2:setHubIcon(galactic_hq_2_hub)
local galactic_hq_3 = DoorSlot("galactic_hq","3")
local galactic_hq_3_hub = DoorSlotHub("galactic_hq","3",galactic_hq_3)
galactic_hq_3:setHubIcon(galactic_hq_3_hub)
local galactic_hq_4 = DoorSlot("galactic_hq","4")
local galactic_hq_4_hub = DoorSlotHub("galactic_hq","4",galactic_hq_4)
galactic_hq_4:setHubIcon(galactic_hq_4_hub)
local galactic_hq_5 = DoorSlot("galactic_hq","5")
local galactic_hq_5_hub = DoorSlotHub("galactic_hq","5",galactic_hq_5)
galactic_hq_5:setHubIcon(galactic_hq_5_hub)
local galactic_hq_6 = DoorSlot("galactic_hq","6")
local galactic_hq_6_hub = DoorSlotHub("galactic_hq","6",galactic_hq_6)
galactic_hq_6:setHubIcon(galactic_hq_6_hub)
local galactic_hq_7 = DoorSlot("galactic_hq","7")
local galactic_hq_7_hub = DoorSlotHub("galactic_hq","7",galactic_hq_7)
galactic_hq_7:setHubIcon(galactic_hq_7_hub)
local galactic_hq_8 = DoorSlot("galactic_hq","8")
local galactic_hq_8_hub = DoorSlotHub("galactic_hq","8",galactic_hq_8)
galactic_hq_8:setHubIcon(galactic_hq_8_hub)
local galactic_hq_9 = DoorSlot("galactic_hq","9")
local galactic_hq_9_hub = DoorSlotHub("galactic_hq","9",galactic_hq_9)
galactic_hq_9:setHubIcon(galactic_hq_9_hub)
local galactic_hq_10 = DoorSlot("galactic_hq","10")
local galactic_hq_10_hub = DoorSlotHub("galactic_hq","10",galactic_hq_10)
galactic_hq_10:setHubIcon(galactic_hq_10_hub)
local galactic_hq_11 = DoorSlot("galactic_hq","11")
local galactic_hq_11_hub = DoorSlotHub("galactic_hq","11",galactic_hq_11)
galactic_hq_11:setHubIcon(galactic_hq_11_hub)
local galactic_hq_12 = DoorSlot("galactic_hq","12")
local galactic_hq_12_hub = DoorSlotHub("galactic_hq","12",galactic_hq_12)
galactic_hq_12:setHubIcon(galactic_hq_12_hub)
local galactic_hq_13 = DoorSlot("galactic_hq","13")
local galactic_hq_13_hub = DoorSlotHub("galactic_hq","13",galactic_hq_13)
galactic_hq_13:setHubIcon(galactic_hq_13_hub)
local galactic_hq_14 = DoorSlot("galactic_hq","14")
local galactic_hq_14_hub = DoorSlotHub("galactic_hq","14",galactic_hq_14)
galactic_hq_14:setHubIcon(galactic_hq_14_hub)
local galactic_hq_15 = DoorSlot("galactic_hq","15")
local galactic_hq_15_hub = DoorSlotHub("galactic_hq","15",galactic_hq_15)
galactic_hq_15:setHubIcon(galactic_hq_15_hub)
local galactic_hq_16 = DoorSlot("galactic_hq","16")
local galactic_hq_16_hub = DoorSlotHub("galactic_hq","16",galactic_hq_16)
galactic_hq_16:setHubIcon(galactic_hq_16_hub)
local galactic_hq_17 = DoorSlot("galactic_hq","17")
local galactic_hq_17_hub = DoorSlotHub("galactic_hq","17",galactic_hq_17)
galactic_hq_17:setHubIcon(galactic_hq_17_hub)
local galactic_hq_18 = DoorSlot("galactic_hq","18")
local galactic_hq_18_hub = DoorSlotHub("galactic_hq","18",galactic_hq_18)
galactic_hq_18:setHubIcon(galactic_hq_18_hub)
local galactic_hq_19 = DoorSlot("galactic_hq","19")
local galactic_hq_19_hub = DoorSlotHub("galactic_hq","19",galactic_hq_19)
galactic_hq_19:setHubIcon(galactic_hq_19_hub)
local galactic_hq_20 = DoorSlot("galactic_hq","20")
local galactic_hq_20_hub = DoorSlotHub("galactic_hq","20",galactic_hq_20)
galactic_hq_20:setHubIcon(galactic_hq_20_hub)
local galactic_hq_21 = DoorSlot("galactic_hq","21")
local galactic_hq_21_hub = DoorSlotHub("galactic_hq","21",galactic_hq_21)
galactic_hq_21:setHubIcon(galactic_hq_21_hub)
local galactic_hq_22 = DoorSlot("galactic_hq","22")
local galactic_hq_22_hub = DoorSlotHub("galactic_hq","22",galactic_hq_22)
galactic_hq_22:setHubIcon(galactic_hq_22_hub)
local galactic_hq_23 = DoorSlot("galactic_hq","23")
local galactic_hq_23_hub = DoorSlotHub("galactic_hq","23",galactic_hq_23)
galactic_hq_23:setHubIcon(galactic_hq_23_hub)
