local hearthome_0 = DoorSlot("hearthome","0")
local hearthome_0_hub = DoorSlotHub("hearthome","0",hearthome_0)
hearthome_0:setHubIcon(hearthome_0_hub)
local hearthome_1 = DoorSlot("hearthome","1")
local hearthome_1_hub = DoorSlotHub("hearthome","1",hearthome_1)
hearthome_1:setHubIcon(hearthome_1_hub)
local hearthome_2 = DoorSlot("hearthome","2")
local hearthome_2_hub = DoorSlotHub("hearthome","2",hearthome_2)
hearthome_2:setHubIcon(hearthome_2_hub)
local hearthome_3 = DoorSlot("hearthome","3")
local hearthome_3_hub = DoorSlotHub("hearthome","3",hearthome_3)
hearthome_3:setHubIcon(hearthome_3_hub)
local hearthome_4 = DoorSlot("hearthome","4")
local hearthome_4_hub = DoorSlotHub("hearthome","4",hearthome_4)
hearthome_4:setHubIcon(hearthome_4_hub)
local hearthome_5 = DoorSlot("hearthome","5")
local hearthome_5_hub = DoorSlotHub("hearthome","5",hearthome_5)
hearthome_5:setHubIcon(hearthome_5_hub)
local hearthome_6 = DoorSlot("hearthome","6")
local hearthome_6_hub = DoorSlotHub("hearthome","6",hearthome_6)
hearthome_6:setHubIcon(hearthome_6_hub)
local hearthome_7 = DoorSlot("hearthome","7")
local hearthome_7_hub = DoorSlotHub("hearthome","7",hearthome_7)
hearthome_7:setHubIcon(hearthome_7_hub)
local hearthome_8 = DoorSlot("hearthome","8")
local hearthome_8_hub = DoorSlotHub("hearthome","8",hearthome_8)
hearthome_8:setHubIcon(hearthome_8_hub)
local hearthome_9 = DoorSlot("hearthome","9")
local hearthome_9_hub = DoorSlotHub("hearthome","9",hearthome_9)
hearthome_9:setHubIcon(hearthome_9_hub)
local hearthome_10 = DoorSlot("hearthome","10")
local hearthome_10_hub = DoorSlotHub("hearthome","10",hearthome_10)
hearthome_10:setHubIcon(hearthome_10_hub)
local hearthome_11 = DoorSlot("hearthome","11")
local hearthome_11_hub = DoorSlotHub("hearthome","11",hearthome_11)
hearthome_11:setHubIcon(hearthome_11_hub)
local hearthome_12 = DoorSlot("hearthome","12")
local hearthome_12_hub = DoorSlotHub("hearthome","12",hearthome_12)
hearthome_12:setHubIcon(hearthome_12_hub)
local hearthome_13 = DoorSlot("hearthome","13")
local hearthome_13_hub = DoorSlotHub("hearthome","13",hearthome_13)
hearthome_13:setHubIcon(hearthome_13_hub)
local hearthome_14 = DoorSlot("hearthome","14")
local hearthome_14_hub = DoorSlotHub("hearthome","14",hearthome_14)
hearthome_14:setHubIcon(hearthome_14_hub)
local hearthome_15 = DoorSlot("hearthome","15")
local hearthome_15_hub = DoorSlotHub("hearthome","15",hearthome_15)
hearthome_15:setHubIcon(hearthome_15_hub)
local hearthome_16 = DoorSlot("hearthome","16")
local hearthome_16_hub = DoorSlotHub("hearthome","16",hearthome_16)
hearthome_16:setHubIcon(hearthome_16_hub)
local hearthome_17 = DoorSlot("hearthome","17")
local hearthome_17_hub = DoorSlotHub("hearthome","17",hearthome_17)
hearthome_17:setHubIcon(hearthome_17_hub)
