local iron_island_0 = DoorSlot("iron_island","0")
local iron_island_0_hub = DoorSlotHub("iron_island","0",iron_island_0)
iron_island_0:setHubIcon(iron_island_0_hub)
local iron_island_1 = DoorSlot("iron_island","1")
local iron_island_1_hub = DoorSlotHub("iron_island","1",iron_island_1)
iron_island_1:setHubIcon(iron_island_1_hub)
local iron_island_2 = DoorSlot("iron_island","2")
local iron_island_2_hub = DoorSlotHub("iron_island","2",iron_island_2)
iron_island_2:setHubIcon(iron_island_2_hub)
local iron_island_3 = DoorSlot("iron_island","3")
local iron_island_3_hub = DoorSlotHub("iron_island","3",iron_island_3)
iron_island_3:setHubIcon(iron_island_3_hub)
local iron_island_4 = DoorSlot("iron_island","4")
local iron_island_4_hub = DoorSlotHub("iron_island","4",iron_island_4)
iron_island_4:setHubIcon(iron_island_4_hub)
local iron_island_5 = DoorSlot("iron_island","5")
local iron_island_5_hub = DoorSlotHub("iron_island","5",iron_island_5)
iron_island_5:setHubIcon(iron_island_5_hub)
local iron_island_6 = DoorSlot("iron_island","6")
local iron_island_6_hub = DoorSlotHub("iron_island","6",iron_island_6)
iron_island_6:setHubIcon(iron_island_6_hub)
local iron_island_7 = DoorSlot("iron_island","7")
local iron_island_7_hub = DoorSlotHub("iron_island","7",iron_island_7)
iron_island_7:setHubIcon(iron_island_7_hub)
local iron_island_8 = DoorSlot("iron_island","8")
local iron_island_8_hub = DoorSlotHub("iron_island","8",iron_island_8)
iron_island_8:setHubIcon(iron_island_8_hub)
local iron_island_9 = DoorSlot("iron_island","9")
local iron_island_9_hub = DoorSlotHub("iron_island","9",iron_island_9)
iron_island_9:setHubIcon(iron_island_9_hub)
local iron_island_10 = DoorSlot("iron_island","10")
local iron_island_10_hub = DoorSlotHub("iron_island","10",iron_island_10)
iron_island_10:setHubIcon(iron_island_10_hub)
local iron_island_11 = DoorSlot("iron_island","11")
local iron_island_11_hub = DoorSlotHub("iron_island","11",iron_island_11)
iron_island_11:setHubIcon(iron_island_11_hub)
