local jubilife_tv_0 = DoorSlot("jubilife_tv","0")
local jubilife_tv_0_hub = DoorSlotHub("jubilife_tv","0",jubilife_tv_0)
jubilife_tv_0:setHubIcon(jubilife_tv_0_hub)
local jubilife_tv_1 = DoorSlot("jubilife_tv","1")
local jubilife_tv_1_hub = DoorSlotHub("jubilife_tv","1",jubilife_tv_1)
jubilife_tv_1:setHubIcon(jubilife_tv_1_hub)
local jubilife_tv_2 = DoorSlot("jubilife_tv","2")
local jubilife_tv_2_hub = DoorSlotHub("jubilife_tv","2",jubilife_tv_2)
jubilife_tv_2:setHubIcon(jubilife_tv_2_hub)
local jubilife_tv_3 = DoorSlot("jubilife_tv","3")
local jubilife_tv_3_hub = DoorSlotHub("jubilife_tv","3",jubilife_tv_3)
jubilife_tv_3:setHubIcon(jubilife_tv_3_hub)
local jubilife_tv_4 = DoorSlot("jubilife_tv","4")
local jubilife_tv_4_hub = DoorSlotHub("jubilife_tv","4",jubilife_tv_4)
jubilife_tv_4:setHubIcon(jubilife_tv_4_hub)
local jubilife_tv_5 = DoorSlot("jubilife_tv","5")
local jubilife_tv_5_hub = DoorSlotHub("jubilife_tv","5",jubilife_tv_5)
jubilife_tv_5:setHubIcon(jubilife_tv_5_hub)
local jubilife_tv_6 = DoorSlot("jubilife_tv","6")
local jubilife_tv_6_hub = DoorSlotHub("jubilife_tv","6",jubilife_tv_6)
jubilife_tv_6:setHubIcon(jubilife_tv_6_hub)
local jubilife_tv_7 = DoorSlot("jubilife_tv","7")
local jubilife_tv_7_hub = DoorSlotHub("jubilife_tv","7",jubilife_tv_7)
jubilife_tv_7:setHubIcon(jubilife_tv_7_hub)
local jubilife_tv_8 = DoorSlot("jubilife_tv","8")
local jubilife_tv_8_hub = DoorSlotHub("jubilife_tv","8",jubilife_tv_8)
jubilife_tv_8:setHubIcon(jubilife_tv_8_hub)
local jubilife_tv_9 = DoorSlot("jubilife_tv","9")
local jubilife_tv_9_hub = DoorSlotHub("jubilife_tv","9",jubilife_tv_9)
jubilife_tv_9:setHubIcon(jubilife_tv_9_hub)
