local jubilife_0 = DoorSlot("jubilife","0")
local jubilife_0_hub = DoorSlotHub("jubilife","0",jubilife_0)
jubilife_0:setHubIcon(jubilife_0_hub)
local jubilife_1 = DoorSlot("jubilife","1")
local jubilife_1_hub = DoorSlotHub("jubilife","1",jubilife_1)
jubilife_1:setHubIcon(jubilife_1_hub)
local jubilife_2 = DoorSlot("jubilife","2")
local jubilife_2_hub = DoorSlotHub("jubilife","2",jubilife_2)
jubilife_2:setHubIcon(jubilife_2_hub)
local jubilife_3 = DoorSlot("jubilife","3")
local jubilife_3_hub = DoorSlotHub("jubilife","3",jubilife_3)
jubilife_3:setHubIcon(jubilife_3_hub)
local jubilife_4 = DoorSlot("jubilife","4")
local jubilife_4_hub = DoorSlotHub("jubilife","4",jubilife_4)
jubilife_4:setHubIcon(jubilife_4_hub)
local jubilife_5 = DoorSlot("jubilife","5")
local jubilife_5_hub = DoorSlotHub("jubilife","5",jubilife_5)
jubilife_5:setHubIcon(jubilife_5_hub)
local jubilife_6 = DoorSlot("jubilife","6")
local jubilife_6_hub = DoorSlotHub("jubilife","6",jubilife_6)
jubilife_6:setHubIcon(jubilife_6_hub)
local jubilife_7 = DoorSlot("jubilife","7")
local jubilife_7_hub = DoorSlotHub("jubilife","7",jubilife_7)
jubilife_7:setHubIcon(jubilife_7_hub)
local jubilife_8 = DoorSlot("jubilife","8")
local jubilife_8_hub = DoorSlotHub("jubilife","8",jubilife_8)
jubilife_8:setHubIcon(jubilife_8_hub)
local jubilife_9 = DoorSlot("jubilife","9")
local jubilife_9_hub = DoorSlotHub("jubilife","9",jubilife_9)
jubilife_9:setHubIcon(jubilife_9_hub)
local jubilife_10 = DoorSlot("jubilife","10")
local jubilife_10_hub = DoorSlotHub("jubilife","10",jubilife_10)
jubilife_10:setHubIcon(jubilife_10_hub)
local jubilife_11 = DoorSlot("jubilife","11")
local jubilife_11_hub = DoorSlotHub("jubilife","11",jubilife_11)
jubilife_11:setHubIcon(jubilife_11_hub)
local jubilife_12 = DoorSlot("jubilife","12")
local jubilife_12_hub = DoorSlotHub("jubilife","12",jubilife_12)
jubilife_12:setHubIcon(jubilife_12_hub)
local jubilife_13 = DoorSlot("jubilife","13")
local jubilife_13_hub = DoorSlotHub("jubilife","13",jubilife_13)
jubilife_13:setHubIcon(jubilife_13_hub)
local jubilife_14 = DoorSlot("jubilife","14")
local jubilife_14_hub = DoorSlotHub("jubilife","14",jubilife_14)
jubilife_14:setHubIcon(jubilife_14_hub)
local jubilife_15 = DoorSlot("jubilife","15")
local jubilife_15_hub = DoorSlotHub("jubilife","15",jubilife_15)
jubilife_15:setHubIcon(jubilife_15_hub)