local league_0 = DoorSlot("league","0")
local league_0_hub = DoorSlotHub("league","0",league_0)
league_0:setHubIcon(league_0_hub)
local league_1 = DoorSlot("league","1")
local league_1_hub = DoorSlotHub("league","1",league_1)
league_1:setHubIcon(league_1_hub)
local league_2 = DoorSlot("league","2")
local league_2_hub = DoorSlotHub("league","2",league_2)
league_2:setHubIcon(league_2_hub)
local league_3 = DoorSlot("league","3")
local league_3_hub = DoorSlotHub("league","3",league_3)
league_3:setHubIcon(league_3_hub)
local league_4 = DoorSlot("league","4")
local league_4_hub = DoorSlotHub("league","4",league_4)
league_4:setHubIcon(league_4_hub)
local league_5 = DoorSlot("league","5")
local league_5_hub = DoorSlotHub("league","5",league_5)
league_5:setHubIcon(league_5_hub)
local league_6 = DoorSlot("league","6")
local league_6_hub = DoorSlotHub("league","6",league_6)
league_6:setHubIcon(league_6_hub)
local league_7 = DoorSlot("league","7")
local league_7_hub = DoorSlotHub("league","7",league_7)
league_7:setHubIcon(league_7_hub)
local league_8 = DoorSlot("league","8")
local league_8_hub = DoorSlotHub("league","8",league_8)
league_8:setHubIcon(league_8_hub)
