local mansion_0 = DoorSlot("mansion","0")
local mansion_0_hub = DoorSlotHub("mansion","0",mansion_0)
mansion_0:setHubIcon(mansion_0_hub)
local mansion_1 = DoorSlot("mansion","1")
local mansion_1_hub = DoorSlotHub("mansion","1",mansion_1)
mansion_1:setHubIcon(mansion_1_hub)
local mansion_2 = DoorSlot("mansion","2")
local mansion_2_hub = DoorSlotHub("mansion","2",mansion_2)
mansion_2:setHubIcon(mansion_2_hub)
local mansion_3 = DoorSlot("mansion","3")
local mansion_3_hub = DoorSlotHub("mansion","3",mansion_3)
mansion_3:setHubIcon(mansion_3_hub)
local mansion_4 = DoorSlot("mansion","4")
local mansion_4_hub = DoorSlotHub("mansion","4",mansion_4)
mansion_4:setHubIcon(mansion_4_hub)
local mansion_5 = DoorSlot("mansion","5")
local mansion_5_hub = DoorSlotHub("mansion","5",mansion_5)
mansion_5:setHubIcon(mansion_5_hub)
