local old_chateau_0 = DoorSlot("old_chateau","0")
local old_chateau_0_hub = DoorSlotHub("old_chateau","0",old_chateau_0)
old_chateau_0:setHubIcon(old_chateau_0_hub)
local old_chateau_1 = DoorSlot("old_chateau","1")
local old_chateau_1_hub = DoorSlotHub("old_chateau","1",old_chateau_1)
old_chateau_1:setHubIcon(old_chateau_1_hub)
local old_chateau_2 = DoorSlot("old_chateau","2")
local old_chateau_2_hub = DoorSlotHub("old_chateau","2",old_chateau_2)
old_chateau_2:setHubIcon(old_chateau_2_hub)
local old_chateau_3 = DoorSlot("old_chateau","3")
local old_chateau_3_hub = DoorSlotHub("old_chateau","3",old_chateau_3)
old_chateau_3:setHubIcon(old_chateau_3_hub)
local old_chateau_4 = DoorSlot("old_chateau","4")
local old_chateau_4_hub = DoorSlotHub("old_chateau","4",old_chateau_4)
old_chateau_4:setHubIcon(old_chateau_4_hub)
local old_chateau_5 = DoorSlot("old_chateau","5")
local old_chateau_5_hub = DoorSlotHub("old_chateau","5",old_chateau_5)
old_chateau_5:setHubIcon(old_chateau_5_hub)
local old_chateau_6 = DoorSlot("old_chateau","6")
local old_chateau_6_hub = DoorSlotHub("old_chateau","6",old_chateau_6)
old_chateau_6:setHubIcon(old_chateau_6_hub)
local old_chateau_7 = DoorSlot("old_chateau","7")
local old_chateau_7_hub = DoorSlotHub("old_chateau","7",old_chateau_7)
old_chateau_7:setHubIcon(old_chateau_7_hub)
local old_chateau_8 = DoorSlot("old_chateau","8")
local old_chateau_8_hub = DoorSlotHub("old_chateau","8",old_chateau_8)
old_chateau_8:setHubIcon(old_chateau_8_hub)
local old_chateau_9 = DoorSlot("old_chateau","9")
local old_chateau_9_hub = DoorSlotHub("old_chateau","9",old_chateau_9)
old_chateau_9:setHubIcon(old_chateau_9_hub)
local old_chateau_10 = DoorSlot("old_chateau","10")
local old_chateau_10_hub = DoorSlotHub("old_chateau","10",old_chateau_10)
old_chateau_10:setHubIcon(old_chateau_10_hub)
local old_chateau_11 = DoorSlot("old_chateau","11")
local old_chateau_11_hub = DoorSlotHub("old_chateau","11",old_chateau_11)
old_chateau_11:setHubIcon(old_chateau_11_hub)