local oreburgh_0 = DoorSlot("oreburgh","0")
local oreburgh_0_hub = DoorSlotHub("oreburgh","0",oreburgh_0)
oreburgh_0:setHubIcon(oreburgh_0_hub)
local oreburgh_1 = DoorSlot("oreburgh","1")
local oreburgh_1_hub = DoorSlotHub("oreburgh","1",oreburgh_1)
oreburgh_1:setHubIcon(oreburgh_1_hub)
local oreburgh_2 = DoorSlot("oreburgh","2")
local oreburgh_2_hub = DoorSlotHub("oreburgh","2",oreburgh_2)
oreburgh_2:setHubIcon(oreburgh_2_hub)
local oreburgh_3 = DoorSlot("oreburgh","3")
local oreburgh_3_hub = DoorSlotHub("oreburgh","3",oreburgh_3)
oreburgh_3:setHubIcon(oreburgh_3_hub)
local oreburgh_4 = DoorSlot("oreburgh","4")
local oreburgh_4_hub = DoorSlotHub("oreburgh","4",oreburgh_4)
oreburgh_4:setHubIcon(oreburgh_4_hub)
local oreburgh_5 = DoorSlot("oreburgh","5")
local oreburgh_5_hub = DoorSlotHub("oreburgh","5",oreburgh_5)
oreburgh_5:setHubIcon(oreburgh_5_hub)
local oreburgh_6 = DoorSlot("oreburgh","6")
local oreburgh_6_hub = DoorSlotHub("oreburgh","6",oreburgh_6)
oreburgh_6:setHubIcon(oreburgh_6_hub)
local oreburgh_7 = DoorSlot("oreburgh","7")
local oreburgh_7_hub = DoorSlotHub("oreburgh","7",oreburgh_7)
oreburgh_7:setHubIcon(oreburgh_7_hub)
local oreburgh_8 = DoorSlot("oreburgh","8")
local oreburgh_8_hub = DoorSlotHub("oreburgh","8",oreburgh_8)
oreburgh_8:setHubIcon(oreburgh_8_hub)
local oreburgh_9 = DoorSlot("oreburgh","9")
local oreburgh_9_hub = DoorSlotHub("oreburgh","9",oreburgh_9)
oreburgh_9:setHubIcon(oreburgh_9_hub)
local oreburgh_10 = DoorSlot("oreburgh","10")
local oreburgh_10_hub = DoorSlotHub("oreburgh","10",oreburgh_10)
oreburgh_10:setHubIcon(oreburgh_10_hub)
local oreburgh_11 = DoorSlot("oreburgh","11")
local oreburgh_11_hub = DoorSlotHub("oreburgh","11",oreburgh_11)
oreburgh_11:setHubIcon(oreburgh_11_hub)
local oreburgh_12 = DoorSlot("oreburgh","12")
local oreburgh_12_hub = DoorSlotHub("oreburgh","12",oreburgh_12)
oreburgh_12:setHubIcon(oreburgh_12_hub)
local oreburgh_13 = DoorSlot("oreburgh","13")
local oreburgh_13_hub = DoorSlotHub("oreburgh","13",oreburgh_13)
oreburgh_13:setHubIcon(oreburgh_13_hub)
local oreburgh_14 = DoorSlot("oreburgh","14")
local oreburgh_14_hub = DoorSlotHub("oreburgh","14",oreburgh_14)
oreburgh_14:setHubIcon(oreburgh_14_hub)
