local oreburgh_gate_0 = DoorSlot("oreburgh_gate","0")
local oreburgh_gate_0_hub = DoorSlotHub("oreburgh_gate","0",oreburgh_gate_0)
oreburgh_gate_0:setHubIcon(oreburgh_gate_0_hub)
local oreburgh_gate_1 = DoorSlot("oreburgh_gate","1")
local oreburgh_gate_1_hub = DoorSlotHub("oreburgh_gate","1",oreburgh_gate_1)
oreburgh_gate_1:setHubIcon(oreburgh_gate_1_hub)
local oreburgh_gate_2 = DoorSlot("oreburgh_gate","2")
local oreburgh_gate_2_hub = DoorSlotHub("oreburgh_gate","2",oreburgh_gate_2)
oreburgh_gate_2:setHubIcon(oreburgh_gate_2_hub)