local pastoria_0 = DoorSlot("pastoria","0")
local pastoria_0_hub = DoorSlotHub("pastoria","0",pastoria_0)
pastoria_0:setHubIcon(pastoria_0_hub)
local pastoria_1 = DoorSlot("pastoria","1")
local pastoria_1_hub = DoorSlotHub("pastoria","1",pastoria_1)
pastoria_1:setHubIcon(pastoria_1_hub)
local pastoria_2 = DoorSlot("pastoria","2")
local pastoria_2_hub = DoorSlotHub("pastoria","2",pastoria_2)
pastoria_2:setHubIcon(pastoria_2_hub)
local pastoria_3 = DoorSlot("pastoria","3")
local pastoria_3_hub = DoorSlotHub("pastoria","3",pastoria_3)
pastoria_3:setHubIcon(pastoria_3_hub)
local pastoria_4 = DoorSlot("pastoria","4")
local pastoria_4_hub = DoorSlotHub("pastoria","4",pastoria_4)
pastoria_4:setHubIcon(pastoria_4_hub)
local pastoria_5 = DoorSlot("pastoria","5")
local pastoria_5_hub = DoorSlotHub("pastoria","5",pastoria_5)
pastoria_5:setHubIcon(pastoria_5_hub)
local pastoria_6 = DoorSlot("pastoria","6")
local pastoria_6_hub = DoorSlotHub("pastoria","6",pastoria_6)
pastoria_6:setHubIcon(pastoria_6_hub)
local pastoria_7 = DoorSlot("pastoria","7")
local pastoria_7_hub = DoorSlotHub("pastoria","7",pastoria_7)
pastoria_7:setHubIcon(pastoria_7_hub)
local pastoria_8 = DoorSlot("pastoria","8")
local pastoria_8_hub = DoorSlotHub("pastoria","8",pastoria_8)
pastoria_8:setHubIcon(pastoria_8_hub)
local pastoria_9 = DoorSlot("pastoria","9")
local pastoria_9_hub = DoorSlotHub("pastoria","9",pastoria_9)
pastoria_9:setHubIcon(pastoria_9_hub)
local pastoria_10 = DoorSlot("pastoria","10")
local pastoria_10_hub = DoorSlotHub("pastoria","10",pastoria_10)
pastoria_10:setHubIcon(pastoria_10_hub)
local pastoria_11 = DoorSlot("pastoria","11")
local pastoria_11_hub = DoorSlotHub("pastoria","11",pastoria_11)
pastoria_11:setHubIcon(pastoria_11_hub)
local pastoria_12 = DoorSlot("pastoria","12")
local pastoria_12_hub = DoorSlotHub("pastoria","12",pastoria_12)
pastoria_12:setHubIcon(pastoria_12_hub)
