local poketch_0 = DoorSlot("poketch","0")
local poketch_0_hub = DoorSlotHub("poketch","0",poketch_0)
poketch_0:setHubIcon(poketch_0_hub)
local poketch_1 = DoorSlot("poketch","1")
local poketch_1_hub = DoorSlotHub("poketch","1",poketch_1)
poketch_1:setHubIcon(poketch_1_hub)
local poketch_2 = DoorSlot("poketch","2")
local poketch_2_hub = DoorSlotHub("poketch","2",poketch_2)
poketch_2:setHubIcon(poketch_2_hub)
