local resort_area_0 = DoorSlot("resort_area","0")
local resort_area_0_hub = DoorSlotHub("resort_area","0",resort_area_0)
resort_area_0:setHubIcon(resort_area_0_hub)
local resort_area_1 = DoorSlot("resort_area","1")
local resort_area_1_hub = DoorSlotHub("resort_area","1",resort_area_1)
resort_area_1:setHubIcon(resort_area_1_hub)
local resort_area_2 = DoorSlot("resort_area","2")
local resort_area_2_hub = DoorSlotHub("resort_area","2",resort_area_2)
resort_area_2:setHubIcon(resort_area_2_hub)
local resort_area_3 = DoorSlot("resort_area","3")
local resort_area_3_hub = DoorSlotHub("resort_area","3",resort_area_3)
resort_area_3:setHubIcon(resort_area_3_hub)
local resort_area_4 = DoorSlot("resort_area","4")
local resort_area_4_hub = DoorSlotHub("resort_area","4",resort_area_4)
resort_area_4:setHubIcon(resort_area_4_hub)
local resort_area_5 = DoorSlot("resort_area","5")
local resort_area_5_hub = DoorSlotHub("resort_area","5",resort_area_5)
resort_area_5:setHubIcon(resort_area_5_hub)
local resort_area_6 = DoorSlot("resort_area","6")
local resort_area_6_hub = DoorSlotHub("resort_area","6",resort_area_6)
resort_area_6:setHubIcon(resort_area_6_hub)
