local sandgem_0 = DoorSlot("sandgem","0")
local sandgem_0_hub = DoorSlotHub("sandgem","0",sandgem_0)
sandgem_0:setHubIcon(sandgem_0_hub)
local sandgem_1 = DoorSlot("sandgem","1")
local sandgem_1_hub = DoorSlotHub("sandgem","1",sandgem_1)
sandgem_1:setHubIcon(sandgem_1_hub)
local sandgem_2 = DoorSlot("sandgem","2")
local sandgem_2_hub = DoorSlotHub("sandgem","2",sandgem_2)
sandgem_2:setHubIcon(sandgem_2_hub)
local sandgem_3 = DoorSlot("sandgem","3")
local sandgem_3_hub = DoorSlotHub("sandgem","3",sandgem_3)
sandgem_3:setHubIcon(sandgem_3_hub)
local sandgem_4 = DoorSlot("sandgem","4")
local sandgem_4_hub = DoorSlotHub("sandgem","4",sandgem_4)
sandgem_4:setHubIcon(sandgem_4_hub)
local sandgem_5 = DoorSlot("sandgem","5")
local sandgem_5_hub = DoorSlotHub("sandgem","5",sandgem_5)
sandgem_5:setHubIcon(sandgem_5_hub)
local sandgem_6 = DoorSlot("sandgem","6")
local sandgem_6_hub = DoorSlotHub("sandgem","6",sandgem_6)
sandgem_6:setHubIcon(sandgem_6_hub)
