local snowpoint_0 = DoorSlot("snowpoint","0")
local snowpoint_0_hub = DoorSlotHub("snowpoint","0",snowpoint_0)
snowpoint_0:setHubIcon(snowpoint_0_hub)
local snowpoint_1 = DoorSlot("snowpoint","1")
local snowpoint_1_hub = DoorSlotHub("snowpoint","1",snowpoint_1)
snowpoint_1:setHubIcon(snowpoint_1_hub)
local snowpoint_2 = DoorSlot("snowpoint","2")
local snowpoint_2_hub = DoorSlotHub("snowpoint","2",snowpoint_2)
snowpoint_2:setHubIcon(snowpoint_2_hub)
local snowpoint_3 = DoorSlot("snowpoint","3")
local snowpoint_3_hub = DoorSlotHub("snowpoint","3",snowpoint_3)
snowpoint_3:setHubIcon(snowpoint_3_hub)
local snowpoint_4 = DoorSlot("snowpoint","4")
local snowpoint_4_hub = DoorSlotHub("snowpoint","4",snowpoint_4)
snowpoint_4:setHubIcon(snowpoint_4_hub)
local snowpoint_5 = DoorSlot("snowpoint","5")
local snowpoint_5_hub = DoorSlotHub("snowpoint","5",snowpoint_5)
snowpoint_5:setHubIcon(snowpoint_5_hub)
local snowpoint_6 = DoorSlot("snowpoint","6")
local snowpoint_6_hub = DoorSlotHub("snowpoint","6",snowpoint_6)
snowpoint_6:setHubIcon(snowpoint_6_hub)
local snowpoint_7 = DoorSlot("snowpoint","7")
local snowpoint_7_hub = DoorSlotHub("snowpoint","7",snowpoint_7)
snowpoint_7:setHubIcon(snowpoint_7_hub)
local snowpoint_8 = DoorSlot("snowpoint","8")
local snowpoint_8_hub = DoorSlotHub("snowpoint","8",snowpoint_8)
snowpoint_8:setHubIcon(snowpoint_8_hub)
