local solaceon_0 = DoorSlot("solaceon","0")
local solaceon_0_hub = DoorSlotHub("solaceon","0",solaceon_0)
solaceon_0:setHubIcon(solaceon_0_hub)
local solaceon_1 = DoorSlot("solaceon","1")
local solaceon_1_hub = DoorSlotHub("solaceon","1",solaceon_1)
solaceon_1:setHubIcon(solaceon_1_hub)
local solaceon_2 = DoorSlot("solaceon","2")
local solaceon_2_hub = DoorSlotHub("solaceon","2",solaceon_2)
solaceon_2:setHubIcon(solaceon_2_hub)
local solaceon_3 = DoorSlot("solaceon","3")
local solaceon_3_hub = DoorSlotHub("solaceon","3",solaceon_3)
solaceon_3:setHubIcon(solaceon_3_hub)
local solaceon_4 = DoorSlot("solaceon","4")
local solaceon_4_hub = DoorSlotHub("solaceon","4",solaceon_4)
solaceon_4:setHubIcon(solaceon_4_hub)
local solaceon_5 = DoorSlot("solaceon","5")
local solaceon_5_hub = DoorSlotHub("solaceon","5",solaceon_5)
solaceon_5:setHubIcon(solaceon_5_hub)
local solaceon_6 = DoorSlot("solaceon","6")
local solaceon_6_hub = DoorSlotHub("solaceon","6",solaceon_6)
solaceon_6:setHubIcon(solaceon_6_hub)
local solaceon_7 = DoorSlot("solaceon","7")
local solaceon_7_hub = DoorSlotHub("solaceon","7",solaceon_7)
solaceon_7:setHubIcon(solaceon_7_hub)
local solaceon_8 = DoorSlot("solaceon","8")
local solaceon_8_hub = DoorSlotHub("solaceon","8",solaceon_8)
solaceon_8:setHubIcon(solaceon_8_hub)
local solaceon_9 = DoorSlot("solaceon","9")
local solaceon_9_hub = DoorSlotHub("solaceon","9",solaceon_9)
solaceon_9:setHubIcon(solaceon_9_hub)
local solaceon_10 = DoorSlot("solaceon","10")
local solaceon_10_hub = DoorSlotHub("solaceon","10",solaceon_10)
solaceon_10:setHubIcon(solaceon_10_hub)
