local solaceon_ruins_0 = DoorSlot("solaceon_ruins","0")
local solaceon_ruins_0_hub = DoorSlotHub("solaceon_ruins","0",solaceon_ruins_0)
solaceon_ruins_0:setHubIcon(solaceon_ruins_0_hub)
local solaceon_ruins_1 = DoorSlot("solaceon_ruins","1")
local solaceon_ruins_1_hub = DoorSlotHub("solaceon_ruins","1",solaceon_ruins_1)
solaceon_ruins_1:setHubIcon(solaceon_ruins_1_hub)
local solaceon_ruins_2 = DoorSlot("solaceon_ruins","2")
local solaceon_ruins_2_hub = DoorSlotHub("solaceon_ruins","2",solaceon_ruins_2)
solaceon_ruins_2:setHubIcon(solaceon_ruins_2_hub)
local solaceon_ruins_3 = DoorSlot("solaceon_ruins","3")
local solaceon_ruins_3_hub = DoorSlotHub("solaceon_ruins","3",solaceon_ruins_3)
solaceon_ruins_3:setHubIcon(solaceon_ruins_3_hub)
local solaceon_ruins_4 = DoorSlot("solaceon_ruins","4")
local solaceon_ruins_4_hub = DoorSlotHub("solaceon_ruins","4",solaceon_ruins_4)
solaceon_ruins_4:setHubIcon(solaceon_ruins_4_hub)
local solaceon_ruins_5 = DoorSlot("solaceon_ruins","5")
local solaceon_ruins_5_hub = DoorSlotHub("solaceon_ruins","5",solaceon_ruins_5)
solaceon_ruins_5:setHubIcon(solaceon_ruins_5_hub)
local solaceon_ruins_6 = DoorSlot("solaceon_ruins","6")
local solaceon_ruins_6_hub = DoorSlotHub("solaceon_ruins","6",solaceon_ruins_6)
solaceon_ruins_6:setHubIcon(solaceon_ruins_6_hub)
local solaceon_ruins_7 = DoorSlot("solaceon_ruins","7")
local solaceon_ruins_7_hub = DoorSlotHub("solaceon_ruins","7",solaceon_ruins_7)
solaceon_ruins_7:setHubIcon(solaceon_ruins_7_hub)
local solaceon_ruins_8 = DoorSlot("solaceon_ruins","8")
local solaceon_ruins_8_hub = DoorSlotHub("solaceon_ruins","8",solaceon_ruins_8)
solaceon_ruins_8:setHubIcon(solaceon_ruins_8_hub)
local solaceon_ruins_9 = DoorSlot("solaceon_ruins","9")
local solaceon_ruins_9_hub = DoorSlotHub("solaceon_ruins","9",solaceon_ruins_9)
solaceon_ruins_9:setHubIcon(solaceon_ruins_9_hub)
local solaceon_ruins_10 = DoorSlot("solaceon_ruins","10")
local solaceon_ruins_10_hub = DoorSlotHub("solaceon_ruins","10",solaceon_ruins_10)
solaceon_ruins_10:setHubIcon(solaceon_ruins_10_hub)
local solaceon_ruins_11 = DoorSlot("solaceon_ruins","11")
local solaceon_ruins_11_hub = DoorSlotHub("solaceon_ruins","11",solaceon_ruins_11)
solaceon_ruins_11:setHubIcon(solaceon_ruins_11_hub)
local solaceon_ruins_12 = DoorSlot("solaceon_ruins","12")
local solaceon_ruins_12_hub = DoorSlotHub("solaceon_ruins","12",solaceon_ruins_12)
solaceon_ruins_12:setHubIcon(solaceon_ruins_12_hub)
local solaceon_ruins_13 = DoorSlot("solaceon_ruins","13")
local solaceon_ruins_13_hub = DoorSlotHub("solaceon_ruins","13",solaceon_ruins_13)
solaceon_ruins_13:setHubIcon(solaceon_ruins_13_hub)
local solaceon_ruins_14 = DoorSlot("solaceon_ruins","14")
local solaceon_ruins_14_hub = DoorSlotHub("solaceon_ruins","14",solaceon_ruins_14)
solaceon_ruins_14:setHubIcon(solaceon_ruins_14_hub)
local solaceon_ruins_15 = DoorSlot("solaceon_ruins","15")
local solaceon_ruins_15_hub = DoorSlotHub("solaceon_ruins","15",solaceon_ruins_15)
solaceon_ruins_15:setHubIcon(solaceon_ruins_15_hub)
local solaceon_ruins_16 = DoorSlot("solaceon_ruins","16")
local solaceon_ruins_16_hub = DoorSlotHub("solaceon_ruins","16",solaceon_ruins_16)
solaceon_ruins_16:setHubIcon(solaceon_ruins_16_hub)
local solaceon_ruins_17 = DoorSlot("solaceon_ruins","17")
local solaceon_ruins_17_hub = DoorSlotHub("solaceon_ruins","17",solaceon_ruins_17)
solaceon_ruins_17:setHubIcon(solaceon_ruins_17_hub)
local solaceon_ruins_18 = DoorSlot("solaceon_ruins","18")
local solaceon_ruins_18_hub = DoorSlotHub("solaceon_ruins","18",solaceon_ruins_18)
solaceon_ruins_18:setHubIcon(solaceon_ruins_18_hub)
local solaceon_ruins_19 = DoorSlot("solaceon_ruins","19")
local solaceon_ruins_19_hub = DoorSlotHub("solaceon_ruins","19",solaceon_ruins_19)
solaceon_ruins_19:setHubIcon(solaceon_ruins_19_hub)
local solaceon_ruins_20 = DoorSlot("solaceon_ruins","20")
local solaceon_ruins_20_hub = DoorSlotHub("solaceon_ruins","20",solaceon_ruins_20)
solaceon_ruins_20:setHubIcon(solaceon_ruins_20_hub)
local solaceon_ruins_21 = DoorSlot("solaceon_ruins","21")
local solaceon_ruins_21_hub = DoorSlotHub("solaceon_ruins","21",solaceon_ruins_21)
solaceon_ruins_21:setHubIcon(solaceon_ruins_21_hub)
local solaceon_ruins_22 = DoorSlot("solaceon_ruins","22")
local solaceon_ruins_22_hub = DoorSlotHub("solaceon_ruins","22",solaceon_ruins_22)
solaceon_ruins_22:setHubIcon(solaceon_ruins_22_hub)
