local sunyshore_0 = DoorSlot("sunyshore","0")
local sunyshore_0_hub = DoorSlotHub("sunyshore","0",sunyshore_0)
sunyshore_0:setHubIcon(sunyshore_0_hub)
local sunyshore_1 = DoorSlot("sunyshore","1")
local sunyshore_1_hub = DoorSlotHub("sunyshore","1",sunyshore_1)
sunyshore_1:setHubIcon(sunyshore_1_hub)
local sunyshore_2 = DoorSlot("sunyshore","2")
local sunyshore_2_hub = DoorSlotHub("sunyshore","2",sunyshore_2)
sunyshore_2:setHubIcon(sunyshore_2_hub)
local sunyshore_3 = DoorSlot("sunyshore","3")
local sunyshore_3_hub = DoorSlotHub("sunyshore","3",sunyshore_3)
sunyshore_3:setHubIcon(sunyshore_3_hub)
local sunyshore_4 = DoorSlot("sunyshore","4")
local sunyshore_4_hub = DoorSlotHub("sunyshore","4",sunyshore_4)
sunyshore_4:setHubIcon(sunyshore_4_hub)
local sunyshore_5 = DoorSlot("sunyshore","5")
local sunyshore_5_hub = DoorSlotHub("sunyshore","5",sunyshore_5)
sunyshore_5:setHubIcon(sunyshore_5_hub)
local sunyshore_6 = DoorSlot("sunyshore","6")
local sunyshore_6_hub = DoorSlotHub("sunyshore","6",sunyshore_6)
sunyshore_6:setHubIcon(sunyshore_6_hub)
local sunyshore_7 = DoorSlot("sunyshore","7")
local sunyshore_7_hub = DoorSlotHub("sunyshore","7",sunyshore_7)
sunyshore_7:setHubIcon(sunyshore_7_hub)
local sunyshore_8 = DoorSlot("sunyshore","8")
local sunyshore_8_hub = DoorSlotHub("sunyshore","8",sunyshore_8)
sunyshore_8:setHubIcon(sunyshore_8_hub)
local sunyshore_9 = DoorSlot("sunyshore","9")
local sunyshore_9_hub = DoorSlotHub("sunyshore","9",sunyshore_9)
sunyshore_9:setHubIcon(sunyshore_9_hub)
local sunyshore_10 = DoorSlot("sunyshore","10")
local sunyshore_10_hub = DoorSlotHub("sunyshore","10",sunyshore_10)
sunyshore_10:setHubIcon(sunyshore_10_hub)
local sunyshore_11 = DoorSlot("sunyshore","11")
local sunyshore_11_hub = DoorSlotHub("sunyshore","11",sunyshore_11)
sunyshore_11:setHubIcon(sunyshore_11_hub)
local sunyshore_12 = DoorSlot("sunyshore","12")
local sunyshore_12_hub = DoorSlotHub("sunyshore","12",sunyshore_12)
sunyshore_12:setHubIcon(sunyshore_12_hub)
