local survival_area_0 = DoorSlot("survival_area","0")
local survival_area_0_hub = DoorSlotHub("survival_area","0",survival_area_0)
survival_area_0:setHubIcon(survival_area_0_hub)
local survival_area_1 = DoorSlot("survival_area","1")
local survival_area_1_hub = DoorSlotHub("survival_area","1",survival_area_1)
survival_area_1:setHubIcon(survival_area_1_hub)
local survival_area_2 = DoorSlot("survival_area","2")
local survival_area_2_hub = DoorSlotHub("survival_area","2",survival_area_2)
survival_area_2:setHubIcon(survival_area_2_hub)
local survival_area_3 = DoorSlot("survival_area","3")
local survival_area_3_hub = DoorSlotHub("survival_area","3",survival_area_3)
survival_area_3:setHubIcon(survival_area_3_hub)
local survival_area_4 = DoorSlot("survival_area","4")
local survival_area_4_hub = DoorSlotHub("survival_area","4",survival_area_4)
survival_area_4:setHubIcon(survival_area_4_hub)
local survival_area_5 = DoorSlot("survival_area","5")
local survival_area_5_hub = DoorSlotHub("survival_area","5",survival_area_5)
survival_area_5:setHubIcon(survival_area_5_hub)
local survival_area_6 = DoorSlot("survival_area","6")
local survival_area_6_hub = DoorSlotHub("survival_area","6",survival_area_6)
survival_area_6:setHubIcon(survival_area_6_hub)
local survival_area_7 = DoorSlot("survival_area","7")
local survival_area_7_hub = DoorSlotHub("survival_area","7",survival_area_7)
survival_area_7:setHubIcon(survival_area_7_hub)
