local valor_lakefront_0 = DoorSlot("valor_lakefront","0")
local valor_lakefront_0_hub = DoorSlotHub("valor_lakefront","0",valor_lakefront_0)
valor_lakefront_0:setHubIcon(valor_lakefront_0_hub)
local valor_lakefront_1 = DoorSlot("valor_lakefront","1")
local valor_lakefront_1_hub = DoorSlotHub("valor_lakefront","1",valor_lakefront_1)
valor_lakefront_1:setHubIcon(valor_lakefront_1_hub)
local valor_lakefront_2 = DoorSlot("valor_lakefront","2")
local valor_lakefront_2_hub = DoorSlotHub("valor_lakefront","2",valor_lakefront_2)
valor_lakefront_2:setHubIcon(valor_lakefront_2_hub)
local valor_lakefront_3 = DoorSlot("valor_lakefront","3")
local valor_lakefront_3_hub = DoorSlotHub("valor_lakefront","3",valor_lakefront_3)
valor_lakefront_3:setHubIcon(valor_lakefront_3_hub)
local valor_lakefront_4 = DoorSlot("valor_lakefront","4")
local valor_lakefront_4_hub = DoorSlotHub("valor_lakefront","4",valor_lakefront_4)
valor_lakefront_4:setHubIcon(valor_lakefront_4_hub)
local valor_lakefront_5 = DoorSlot("valor_lakefront","5")
local valor_lakefront_5_hub = DoorSlotHub("valor_lakefront","5",valor_lakefront_5)
valor_lakefront_5:setHubIcon(valor_lakefront_5_hub)
local valor_lakefront_6 = DoorSlot("valor_lakefront","6")
local valor_lakefront_6_hub = DoorSlotHub("valor_lakefront","6",valor_lakefront_6)
valor_lakefront_6:setHubIcon(valor_lakefront_6_hub)
local valor_lakefront_7 = DoorSlot("valor_lakefront","7")
local valor_lakefront_7_hub = DoorSlotHub("valor_lakefront","7",valor_lakefront_7)
valor_lakefront_7:setHubIcon(valor_lakefront_7_hub)
