local veilstone_0 = DoorSlot("veilstone","0")
local veilstone_0_hub = DoorSlotHub("veilstone","0",veilstone_0)
veilstone_0:setHubIcon(veilstone_0_hub)
local veilstone_1 = DoorSlot("veilstone","1")
local veilstone_1_hub = DoorSlotHub("veilstone","1",veilstone_1)
veilstone_1:setHubIcon(veilstone_1_hub)
local veilstone_2 = DoorSlot("veilstone","2")
local veilstone_2_hub = DoorSlotHub("veilstone","2",veilstone_2)
veilstone_2:setHubIcon(veilstone_2_hub)
local veilstone_3 = DoorSlot("veilstone","3")
local veilstone_3_hub = DoorSlotHub("veilstone","3",veilstone_3)
veilstone_3:setHubIcon(veilstone_3_hub)
local veilstone_4 = DoorSlot("veilstone","4")
local veilstone_4_hub = DoorSlotHub("veilstone","4",veilstone_4)
veilstone_4:setHubIcon(veilstone_4_hub)
local veilstone_5 = DoorSlot("veilstone","5")
local veilstone_5_hub = DoorSlotHub("veilstone","5",veilstone_5)
veilstone_5:setHubIcon(veilstone_5_hub)
local veilstone_6 = DoorSlot("veilstone","6")
local veilstone_6_hub = DoorSlotHub("veilstone","6",veilstone_6)
veilstone_6:setHubIcon(veilstone_6_hub)
local veilstone_7 = DoorSlot("veilstone","7")
local veilstone_7_hub = DoorSlotHub("veilstone","7",veilstone_7)
veilstone_7:setHubIcon(veilstone_7_hub)
local veilstone_8 = DoorSlot("veilstone","8")
local veilstone_8_hub = DoorSlotHub("veilstone","8",veilstone_8)
veilstone_8:setHubIcon(veilstone_8_hub)
local veilstone_9 = DoorSlot("veilstone","9")
local veilstone_9_hub = DoorSlotHub("veilstone","9",veilstone_9)
veilstone_9:setHubIcon(veilstone_9_hub)
local veilstone_10 = DoorSlot("veilstone","10")
local veilstone_10_hub = DoorSlotHub("veilstone","10",veilstone_10)
veilstone_10:setHubIcon(veilstone_10_hub)
local veilstone_11 = DoorSlot("veilstone","11")
local veilstone_11_hub = DoorSlotHub("veilstone","11",veilstone_11)
veilstone_11:setHubIcon(veilstone_11_hub)
local veilstone_12 = DoorSlot("veilstone","12")
local veilstone_12_hub = DoorSlotHub("veilstone","12",veilstone_12)
veilstone_12:setHubIcon(veilstone_12_hub)
local veilstone_13 = DoorSlot("veilstone","13")
local veilstone_13_hub = DoorSlotHub("veilstone","13",veilstone_13)
veilstone_13:setHubIcon(veilstone_13_hub)
local veilstone_14 = DoorSlot("veilstone","14")
local veilstone_14_hub = DoorSlotHub("veilstone","14",veilstone_14)
veilstone_14:setHubIcon(veilstone_14_hub)
local veilstone_15 = DoorSlot("veilstone","15")
local veilstone_15_hub = DoorSlotHub("veilstone","15",veilstone_15)
veilstone_15:setHubIcon(veilstone_15_hub)
local veilstone_16 = DoorSlot("veilstone","16")
local veilstone_16_hub = DoorSlotHub("veilstone","16",veilstone_16)
veilstone_16:setHubIcon(veilstone_16_hub)
local veilstone_17 = DoorSlot("veilstone","17")
local veilstone_17_hub = DoorSlotHub("veilstone","17",veilstone_17)
veilstone_17:setHubIcon(veilstone_17_hub)
