local victory_road_0 = DoorSlot("victory_road","0")
local victory_road_0_hub = DoorSlotHub("victory_road","0",victory_road_0)
victory_road_0:setHubIcon(victory_road_0_hub)
local victory_road_1 = DoorSlot("victory_road","1")
local victory_road_1_hub = DoorSlotHub("victory_road","1",victory_road_1)
victory_road_1:setHubIcon(victory_road_1_hub)
local victory_road_2 = DoorSlot("victory_road","2")
local victory_road_2_hub = DoorSlotHub("victory_road","2",victory_road_2)
victory_road_2:setHubIcon(victory_road_2_hub)
local victory_road_3 = DoorSlot("victory_road","3")
local victory_road_3_hub = DoorSlotHub("victory_road","3",victory_road_3)
victory_road_3:setHubIcon(victory_road_3_hub)
local victory_road_4 = DoorSlot("victory_road","4")
local victory_road_4_hub = DoorSlotHub("victory_road","4",victory_road_4)
victory_road_4:setHubIcon(victory_road_4_hub)
local victory_road_5 = DoorSlot("victory_road","5")
local victory_road_5_hub = DoorSlotHub("victory_road","5",victory_road_5)
victory_road_5:setHubIcon(victory_road_5_hub)
local victory_road_6 = DoorSlot("victory_road","6")
local victory_road_6_hub = DoorSlotHub("victory_road","6",victory_road_6)
victory_road_6:setHubIcon(victory_road_6_hub)
local victory_road_7 = DoorSlot("victory_road","7")
local victory_road_7_hub = DoorSlotHub("victory_road","7",victory_road_7)
victory_road_7:setHubIcon(victory_road_7_hub)
local victory_road_9 = DoorSlot("victory_road","9")
local victory_road_9_hub = DoorSlotHub("victory_road","9",victory_road_9)
victory_road_9:setHubIcon(victory_road_9_hub)
local victory_road_10 = DoorSlot("victory_road","10")
local victory_road_10_hub = DoorSlotHub("victory_road","10",victory_road_10)
victory_road_10:setHubIcon(victory_road_10_hub)
local victory_road_11 = DoorSlot("victory_road","11")
local victory_road_11_hub = DoorSlotHub("victory_road","11",victory_road_11)
victory_road_11:setHubIcon(victory_road_11_hub)
